### ISSUE TITLE
Component Mountin Lab...Glitchy, can't run tests

### ISSUE THREAD

**Issue by laurenhalpert** [learn-co-curriculum/react-hooks-component-mounting-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/6199/assignments/229258?module_item_id=536173

### Concern

when running npm install and npm test you get an error about exporting objects not functions and was unable to get it working even with help of TC

**Comment by ddeleon267** [comment]
Wanted to add onto this issue - the coach that worked with this student offered this context:

Student was getting errors that seem to be related to babel when running **npm start** and **npm test**:

`src/App.js
  Line 0:  Parsing error: Plugin/Preset files are not allowed to export objects, only functions. `
  
  From the coach:
  
  We were able to get the application to render without errors by creating a .babelrc file in the root directory and putting {
"presets": [
"@babel/preset-env",
"@babel/preset-react"
],
"plugins": [
"transform-class-properties",
"transform-object-rest-spread"
]
}
But the tests did not like the package.json and .babelrc file being there .
We tried combining the code into the babel portion of the package.json but that did not help.  This lab is optional but seems like it might be outdated to the point of not working anymore.
